language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24

script:
  - ./gradlew test --console=plain

after_success:
  - ./gradlew :meter:coveralls --console=plain
